"""add_ustawienia_to_uzytkownik

Revision ID: 0e1e1c481a67
Revises: b6aa70614aa5
Create Date: 2026-04-13 01:26:32.360172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1e1c481a67'
down_revision = 'b6aa70614aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uzytkownicy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ustawienia', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uzytkownicy', schema=None) as batch_op:
        batch_op.drop_column('ustawienia')

    # ### end Alembic commands ###
