"""add sedziowie fields to zawody

Revision ID: 11d2302fbade
Revises: c757e04abb86
Create Date: 2026-04-11 21:02:29.153995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d2302fbade'
down_revision = 'c757e04abb86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zawody', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sedziowie_sektorowi', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sedziowie_kontrolni', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sekretarz_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_zawody_sekretarz_id', 'sedziowie', ['sekretarz_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zawody', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sekretarz_id')
        batch_op.drop_column('sedziowie_kontrolni')
        batch_op.drop_column('sedziowie_sektorowi')

    # ### end Alembic commands ###
