"""add_rodo_zgoda_to_zawodnik

Revision ID: 5ac889f1cdfa
Revises: ff9036fc3e75
Create Date: 2026-04-13 00:36:08.930606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac889f1cdfa'
down_revision = 'ff9036fc3e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zawodnicy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rodo_zgoda', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zawodnicy', schema=None) as batch_op:
        batch_op.drop_column('rodo_zgoda')

    # ### end Alembic commands ###
