"""add_organizator_kolo_and_gatunek_ryby

Revision ID: 6772b52f8436
Revises: 11d2302fbade
Create Date: 2026-04-12 20:37:29.752754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6772b52f8436'
down_revision = '11d2302fbade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gatunki_ryb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=64), nullable=False),
    sa.Column('wymiar_ochronny_mm', sa.Integer(), nullable=False),
    sa.Column('wymiar_punktowany_mm', sa.Integer(), nullable=False),
    sa.Column('punkty_bazowe', sa.Integer(), nullable=False),
    sa.Column('punkty_za_mm', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    with op.batch_alter_table('zawody', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizator_kolo', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zawody', schema=None) as batch_op:
        batch_op.drop_column('organizator_kolo')

    op.drop_table('gatunki_ryb')
    # ### end Alembic commands ###
