"""add_data_do_to_zawody

Revision ID: aa51ccecf94f
Revises: 6772b52f8436
Create Date: 2026-04-12 20:46:58.161782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa51ccecf94f'
down_revision = '6772b52f8436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zawody', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_do', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zawody', schema=None) as batch_op:
        batch_op.drop_column('data_do')

    # ### end Alembic commands ###
