"""add_dokument_model

Revision ID: b6aa70614aa5
Revises: 5ac889f1cdfa
Create Date: 2026-04-13 00:53:09.059479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6aa70614aa5'
down_revision = '5ac889f1cdfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dokumenty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=32), nullable=False),
    sa.Column('tytul', sa.String(length=128), nullable=False),
    sa.Column('tresc', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dokumenty')
    # ### end Alembic commands ###
