"""initial schema

Revision ID: c757e04abb86
Revises: 
Create Date: 2026-03-31 22:37:37.578095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c757e04abb86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dyscypliny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=64), nullable=False),
    sa.Column('kod', sa.String(length=16), nullable=False),
    sa.Column('typ_wyniku', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod'),
    sa.UniqueConstraint('nazwa')
    )
    op.create_table('lowiska',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=128), nullable=False),
    sa.Column('miejscowosc', sa.String(length=128), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sedziowie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=64), nullable=False),
    sa.Column('nazwisko', sa.String(length=64), nullable=False),
    sa.Column('telefon', sa.String(length=32), nullable=True),
    sa.Column('kolo', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zawodnicy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=64), nullable=False),
    sa.Column('nazwisko', sa.String(length=64), nullable=False),
    sa.Column('kolo', sa.String(length=128), nullable=False),
    sa.Column('nr_licencji', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imie', 'nazwisko', 'kolo', name='uq_zawodnik'),
    sa.UniqueConstraint('nr_licencji')
    )
    op.create_table('uzytkownicy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('haslo_hash', sa.String(length=255), nullable=False),
    sa.Column('rola', sa.String(length=16), nullable=False),
    sa.Column('aktywny', sa.Boolean(), nullable=True),
    sa.Column('ostatnie_logowanie', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sedzia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sedzia_id'], ['sedziowie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('zawody',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr_zawodow', sa.String(length=32), nullable=True),
    sa.Column('nazwa', sa.String(length=256), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('godzina_start', sa.Time(), nullable=True),
    sa.Column('godzina_koniec', sa.Time(), nullable=True),
    sa.Column('kategoria', sa.String(length=64), nullable=True),
    sa.Column('rejon', sa.String(length=64), nullable=True),
    sa.Column('liczba_sektorow', sa.Integer(), nullable=False),
    sa.Column('liczba_tur', sa.Integer(), nullable=False),
    sa.Column('grand_prix', sa.Boolean(), nullable=True),
    sa.Column('klasyfikacja_druzynowa', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('uwagi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dyscyplina_id', sa.Integer(), nullable=False),
    sa.Column('lowisko_id', sa.Integer(), nullable=True),
    sa.Column('organizator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dyscyplina_id'], ['dyscypliny.id'], ),
    sa.ForeignKeyConstraint(['lowisko_id'], ['lowiska.id'], ),
    sa.ForeignKeyConstraint(['organizator_id'], ['sedziowie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uczestnicy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numer_startowy', sa.Integer(), nullable=True),
    sa.Column('druzyna', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('zawody_id', sa.Integer(), nullable=False),
    sa.Column('zawodnik_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zawodnik_id'], ['zawodnicy.id'], ),
    sa.ForeignKeyConstraint(['zawody_id'], ['zawody.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zawody_id', 'zawodnik_id', name='uq_uczestnik')
    )
    op.create_table('zawody_sedziowie',
    sa.Column('zawody_id', sa.Integer(), nullable=False),
    sa.Column('sedzia_id', sa.Integer(), nullable=False),
    sa.Column('rola_na_zawodach', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sedzia_id'], ['sedziowie.id'], ),
    sa.ForeignKeyConstraint(['zawody_id'], ['zawody.id'], ),
    sa.PrimaryKeyConstraint('zawody_id', 'sedzia_id')
    )
    op.create_table('stanowiska',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tura', sa.Integer(), nullable=False),
    sa.Column('sektor', sa.String(length=8), nullable=False),
    sa.Column('numer', sa.Integer(), nullable=False),
    sa.Column('zawody_id', sa.Integer(), nullable=False),
    sa.Column('uczestnik_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uczestnik_id'], ['uczestnicy.id'], ),
    sa.ForeignKeyConstraint(['zawody_id'], ['zawody.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zawody_id', 'tura', 'sektor', 'numer', name='uq_stanowisko')
    )
    op.create_table('wyniki_karpie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liczba_sztuk', sa.Integer(), nullable=False),
    sa.Column('waga_g', sa.Integer(), nullable=False),
    sa.Column('najciezsza_g', sa.Integer(), nullable=False),
    sa.Column('punkty_karne', sa.Integer(), nullable=False),
    sa.Column('uwagi', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('stanowisko_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stanowisko_id'], ['stanowiska.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wyniki_ryby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gatunek', sa.String(length=64), nullable=False),
    sa.Column('dlugosc_mm', sa.Integer(), nullable=False),
    sa.Column('punkty', sa.Integer(), nullable=False),
    sa.Column('zaliczona', sa.Boolean(), nullable=True),
    sa.Column('uwagi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('stanowisko_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stanowisko_id'], ['stanowiska.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wyniki_wagowe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waga_g', sa.Integer(), nullable=False),
    sa.Column('dyskwalifikacja', sa.Boolean(), nullable=True),
    sa.Column('uwagi', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('stanowisko_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stanowisko_id'], ['stanowiska.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wyniki_wagowe')
    op.drop_table('wyniki_ryby')
    op.drop_table('wyniki_karpie')
    op.drop_table('stanowiska')
    op.drop_table('zawody_sedziowie')
    op.drop_table('uczestnicy')
    op.drop_table('zawody')
    op.drop_table('uzytkownicy')
    op.drop_table('zawodnicy')
    op.drop_table('sedziowie')
    op.drop_table('lowiska')
    op.drop_table('dyscypliny')
    # ### end Alembic commands ###
