"""add_sezon_to_zawody

Revision ID: ff9036fc3e75
Revises: aa51ccecf94f
Create Date: 2026-04-12 22:29:08.721498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9036fc3e75'
down_revision = 'aa51ccecf94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zawody', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sezon', sa.Integer(), nullable=False, server_default='2025'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zawody', schema=None) as batch_op:
        batch_op.drop_column('sezon')

    # ### end Alembic commands ###
